apiVersion: v1alpha1
kind: "Role"
metadata:
  name: uni-halo-role-template-view-audit-data
  labels:
    halo.run/role-template: "true"
    rbac.authorization.halo.run/aggregate-to-admin: "true"
  annotations:
    rbac.authorization.halo.run/module: "[UH] 审核模式"
    rbac.authorization.halo.run/display-name: "审核模式查看"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:uni-halo:audit-data:view"]
rules:
  - apiGroups: [ "console.api.unihalo.ialley.cn" ]
    resources:
      - "audit-data"
    verbs: [ "get", "list" ]

---

apiVersion: v1alpha1
kind: "Role"
metadata:
  name: uni-halo-role-template-manage-audit-data
  labels:
    halo.run/role-template: "true"
    rbac.authorization.halo.run/aggregate-to-admin: "true"
  annotations:
    rbac.authorization.halo.run/dependencies: |
      [ "uni-halo-role-template-view-audit-data" ]
    rbac.authorization.halo.run/module: "[UH] 审核模式"
    rbac.authorization.halo.run/display-name: "审核模式管理"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:uni-halo:audit-data:manage"]
rules:
  - apiGroups: [ "console.api.unihalo.ialley.cn" ]
    resources:
      - "audit-data"
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]
