apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: uni-halo-plugin
spec:
  enabled: true
  requires: ">=2.26.0"
  author:
    name: 小莫唐尼
    website: https://www.xiaoxiaomo.cn/
  logo: logo.png
  homepage: https://uni-halo.ialley.cn/
  repo: https://github.com/uni-halo/uni-halo-plugin
  issues: https://github.com/uni-halo/uni-halo-plugin/issues
  displayName: "Uni Halo"
  description: "为 UniHalo v3.x 移动端提供配置管理。"
  settingName: uni-halo-plugin-settings
  configMapName: uni-halo-plugin-configmap
  license:
    - name: "GPL-3.0"
      url: "https://github.com/uni-halo/uni-halo-plugin/blob/main/LICENSE"
